baseurl = "https://frlharidon.github.io/"
canonifyurls = true
copyright = "Code released under the Apache 2.0 license."
defaultContentLanguage = "fr"
languageCode = "fr"
paginate = 10
theme = "startbootstrap-clean-blog"
title = "Plomberie du Blavet"
[author]
    name = "Plomberie du Blavet"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "La plomberie du Blavet"
  Author = "Plomberie du Blavet"
  email = "frlharidon@gmail.com"
  Ganalytics = "XX-00000000-0"
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]

[[params.social]]
title = "twitter"
url = "https://twitter.com/humboldtux"
[[params.social]]
    title = "github"
    url = "https://github.com/thibautdavoult"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/FACEBOOKHANDLE"
