baseurl = "https://frlharidon.github.io/"
canonifyurls = true
copyright = "Code released under the Apache 2.0 license."
defaultContentLanguage = "fr"
languageCode = "fr"
paginate = 10
theme = "startbootstrap-clean-blog"
title = "Plomberie du Blavet"
[author]
name = "Thibaut Davoult"
[[menu.main]]
name = "Nos prestations"
url = "/post/"
weight = 2
[[menu.main]]
name = "Réalisations"
url = "/post/"
weight = 4
[params]
Author = "Thibaut Davoult"
DateForm = "Mon, Jan 2, 2006"
Description = "La plomberie du Blavet"
Ganalytics = "XX-00000000-0"
email = "frlharidon@gmail.com"
[[params.social]]
title = "twitter"
url = "https://twitter.com/humboldtux"
[[params.social]]
title = "github"
url = "https://github.com/humboldtux"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/FACEBOOKHANDLE"
