baseurl = "https://frlharidon.github.io/"
title = "Plomberie du Blavet"
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
# themesDir = "../../"
languageCode = "fr"
defaultContentLanguage = "fr"
copyright = "Code released under the Apache 2.0 license."

[author]
    name = "Thibaut Davoult"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "La plomberie du Blavet"
  Author = "Thibaut Davoult"
  email = "frlharidon@gmail.com"
  Ganalytics = "XX-00000000-0"
  # This will load all the CSS defined in the list
  # customCSS = ["<absolute path to CSS>", "/static/css/test.css", "<or just load it off the internet>"]

[[params.social]]
    title = "twitter"
    url = "https://twitter.com/humboldtux"
[[params.social]]
    title = "github"
    url = "https://github.com/humboldtux"
[[params.social]]
    title = "facebook"
    url = "https://www.facebook.com/FACEBOOKHANDLE"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
